GET http://localhost:3002/


###


POST http://localhost:3002/try-post
Content-Type: :application/x-www-form-urlencoded

a=12&b=34


###


POST http://localhost:3002/try-post
Content-Type: application/json

{
    "a":12,
    "name":"Alan"
}